export const FETCH_DL_STEPS = 'FETCH_DL_STEPS';
export const LOADING_DL_STEPS = 'LOADING_DL_STEPS';
export const LOADING_DL_STEPS_FAILURE = 'LOADING_DL_STEPS_FAILURE';
export const RECEIVE_DL_STEPS = 'RECEIVE_DL_STEPS';

export const SAVING_DL_STEP = 'SAVING_DL_STEP';
export const SAVING_DL_STEP_FAILURE = 'SAVING_DL_STEP_FAILURE';
export const RECEIVE_DL_STEP = 'RECEIVE_DL_STEP';

export const DELETE_DL_STEP = 'DELETE_DL_STEP';
export const DELETE_DL_STEP_FAILURE = 'DELETE_DL_STEP_FAILURE';

export const LOADING_DL_TIMINGS = 'LOADING_DL_TIMINGS';
export const LOADING_DL_TIMINGS_FAILURE = 'LOADING_DL_TIMINGS_FAILURE';
export const RECEIVE_DL_TIMINGS = 'RECEIVE_DL_TIMINGS';

export const SAVING_DL_TIMING = 'SAVING_DL_TIMING';
export const SAVING_DL_TIMING_FAILURE = 'SAVING_DL_TIMING_FAILURE';
export const RECEIVE_DL_TIMING = 'RECEIVE_DL_TIMING';

export const DELETE_DL_TIMING = 'DELETE_DL_TIMING';
export const DELETE_DL_TIMING_FAILURE = 'DELETE_DL_TIMING_FAILURE';

export const SELECT_DL_STEP = 'SELECT_DL_STEP';
export const SELECT_DL_TIMING = 'SELECT_DL_TIMING';

export const LOADING_DL_STEP_USAGE = 'LOADING_DL_STEP_USAGE';
export const LOADING_DL_STEP_USAGE_FAILURE = 'LOADING_DL_STEP_USAGE_FAILURE';
export const RECEIVE_DL_STEP_USAGE = 'RECEIVE_DL_STEP_USAGE';
